//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGym.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pemex.Sigec.Backend.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos datos introducidos no son válidos..
        /// </summary>
        internal static string AlgunosDatosIntroducidosNoSonValidos {
            get {
                return ResourceManager.GetString("AlgunosDatosIntroducidosNoSonValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se proporcionó el archivo requerido..
        /// </summary>
        internal static string ArchivoRequeridoNoProporcionado {
            get {
                return ResourceManager.GetString("ArchivoRequeridoNoProporcionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de consulta no válido: {0}..
        /// </summary>
        internal static string CodigoConsultaNoValido {
            get {
                return ResourceManager.GetString("CodigoConsultaNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo no existe en el directorio..
        /// </summary>
        internal static string CorreoNoExisteDirectorioActivo {
            get {
                return ResourceManager.GetString("CorreoNoExisteDirectorioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo ya existe con otro RFC..
        /// </summary>
        internal static string CorreoYaExisteConOtroRfc {
            get {
                return ResourceManager.GetString("CorreoYaExisteConOtroRfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento con datos en conflicto..
        /// </summary>
        internal static string ElementoConflicto {
            get {
                return ResourceManager.GetString("ElementoConflicto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento duplicado..
        /// </summary>
        internal static string ElementoDuplicado {
            get {
                return ResourceManager.GetString("ElementoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento no encontrado..
        /// </summary>
        internal static string ElementoNoEncontrado {
            get {
                return ResourceManager.GetString("ElementoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementos duplicados..
        /// </summary>
        internal static string ElementosDuplicados {
            get {
                return ResourceManager.GetString("ElementosDuplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol solicitado no está autorizado para el usuario..
        /// </summary>
        internal static string ElRolSolicitadoNoEstaAutorizadoParaElUsuario {
            get {
                return ResourceManager.GetString("ElRolSolicitadoNoEstaAutorizadoParaElUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya cuenta con acceso al contrato con el rol solicitado..
        /// </summary>
        internal static string ElUsuarioYaCuentaConAccesoAlContratoConElRolSolicitado {
            get {
                return ResourceManager.GetString("ElUsuarioYaCuentaConAccesoAlContratoConElRolSolicitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya cuenta con acceso al contrato en el período solicitado..
        /// </summary>
        internal static string ElUsuarioYaCuentaConAccesoAlContratoEnPeriodoSolicitado {
            get {
                return ResourceManager.GetString("ElUsuarioYaCuentaConAccesoAlContratoEnPeriodoSolicitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya cuenta con acceso al contrato solicitado..
        /// </summary>
        internal static string ElUsuarioYaCuentaConAccesoAlContratoSolicitado {
            get {
                return ResourceManager.GetString("ElUsuarioYaCuentaConAccesoAlContratoSolicitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato no válido..
        /// </summary>
        internal static string FormatoNoValido {
            get {
                return ResourceManager.GetString("FormatoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato no válido para el tipo.
        /// </summary>
        internal static string FormatoNoValidoParaElTipo {
            get {
                return ResourceManager.GetString("FormatoNoValidoParaElTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se proporcionó la información del archivo..
        /// </summary>
        internal static string InfoArchivoNoProporcionada {
            get {
                return ResourceManager.GetString("InfoArchivoNoProporcionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no puede ser aprobada porque ya ha sido procesada..
        /// </summary>
        internal static string LaSolicitudNoPuedeAprobarsePorqueYaHaSidoProcesada {
            get {
                return ResourceManager.GetString("LaSolicitudNoPuedeAprobarsePorqueYaHaSidoProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no puede ser cancelada porque ya ha sido procesada..
        /// </summary>
        internal static string LaSolicitudNoPuedeCancelarsePorqueYaHaSidoProcesada {
            get {
                return ResourceManager.GetString("LaSolicitudNoPuedeCancelarsePorqueYaHaSidoProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no puede ser rechazada porque ya ha sido procesada..
        /// </summary>
        internal static string LaSolicitudNoPuedeRechazarsePorqueYaHaSidoProcesada {
            get {
                return ResourceManager.GetString("LaSolicitudNoPuedeRechazarsePorqueYaHaSidoProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo excede el tamaño máximo permitido: {0}.
        /// </summary>
        internal static string LongitudArchivoNoPermitidaX {
            get {
                return ResourceManager.GetString("LongitudArchivoNoPermitidaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de archivo no válido..
        /// </summary>
        internal static string LongitudArchivoNoValida {
            get {
                return ResourceManager.GetString("LongitudArchivoNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud máxima permitida es de {0} caracteres..
        /// </summary>
        internal static string LongitudMaximaPermitidaX {
            get {
                return ResourceManager.GetString("LongitudMaximaPermitidaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible convertir valor al tipo.
        /// </summary>
        internal static string NoEsPosibleConvertirValorAlTipo {
            get {
                return ResourceManager.GetString("NoEsPosibleConvertirValorAlTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de archivo no válido..
        /// </summary>
        internal static string NombreArchivoNoValido {
            get {
                return ResourceManager.GetString("NombreArchivoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el elemento con identificador {0}..
        /// </summary>
        internal static string NoSeEncontroElementoConId {
            get {
                return ResourceManager.GetString("NoSeEncontroElementoConId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la unidad de acceso individual para la cuenta de usuario..
        /// </summary>
        internal static string NoSeEncontroUnidadAccesoIndividualParaCuentaUsuario {
            get {
                return ResourceManager.GetString("NoSeEncontroUnidadAccesoIndividualParaCuentaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo ejecutar la operación solicitada..
        /// </summary>
        internal static string NoSePudoEjecutarLaOperacionSolicitada {
            get {
                return ResourceManager.GetString("NoSePudoEjecutarLaOperacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la información solicitada..
        /// </summary>
        internal static string NoSePudoObtenerInformacionSolicitada {
            get {
                return ResourceManager.GetString("NoSePudoObtenerInformacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros con valores no válidos: {0}.
        /// </summary>
        internal static string ParametrosInvalidos {
            get {
                return ResourceManager.GetString("ParametrosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes parámetros requeridos no fueron proporcionados: {0}.
        /// </summary>
        internal static string ParametrosNoProporcionados {
            get {
                return ResourceManager.GetString("ParametrosNoProporcionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros no válidos para la consulta {0}..
        /// </summary>
        internal static string ParametrosNoValidosParaConsulta {
            get {
                return ResourceManager.GetString("ParametrosNoValidosParaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de fechas no válido..
        /// </summary>
        internal static string RengoFechasNoValido {
            get {
                return ResourceManager.GetString("RengoFechasNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC proporcionado es distinto al que se encuentra registrado..
        /// </summary>
        internal static string RfcProporcionadoDistintoRegistrado {
            get {
                return ResourceManager.GetString("RfcProporcionadoDistintoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de archivo no permitido: {0}..
        /// </summary>
        internal static string TipoArchivoNoPermitidoX {
            get {
                return ResourceManager.GetString("TipoArchivoNoPermitidoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de error no válido: {0}.
        /// </summary>
        internal static string TipoErrorNoValido {
            get {
                return ResourceManager.GetString("TipoErrorNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de nombramiento o fechas en conflicto con el acceso concedido actualmente..
        /// </summary>
        internal static string TipoOFechasNombramientoEnConflictoConAccesoActual {
            get {
                return ResourceManager.GetString("TipoOFechasNombramientoEnConflictoConAccesoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor es muy grande o muy pequeño para el tipo.
        /// </summary>
        internal static string ValorGrandePequenoParaElTipo {
            get {
                return ResourceManager.GetString("ValorGrandePequenoParaElTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor no permitido..
        /// </summary>
        internal static string ValorNoPermitido {
            get {
                return ResourceManager.GetString("ValorNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor &apos;{0}&apos; no válido para el parámetro &apos;{1}&apos;..
        /// </summary>
        internal static string ValorParametroNoValido {
            get {
                return ResourceManager.GetString("ValorParametroNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro es nulo.
        /// </summary>
        internal static string ValorParametroNulo {
            get {
                return ResourceManager.GetString("ValorParametroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor requerido..
        /// </summary>
        internal static string ValorRequerido {
            get {
                return ResourceManager.GetString("ValorRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión no válida..
        /// </summary>
        internal static string VersionNoValida {
            get {
                return ResourceManager.GetString("VersionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un elemento identificado por el valor &apos;{0}&apos;..
        /// </summary>
        internal static string YaExisteElementoX {
            get {
                return ResourceManager.GetString("YaExisteElementoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha solicitado acceso al contrato..
        /// </summary>
        internal static string YaSeHaSolicitadoAccesoContrato {
            get {
                return ResourceManager.GetString("YaSeHaSolicitadoAccesoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha solicitado acceso al contrato con el rol especificado.
        /// </summary>
        internal static string YaSeHaSolicitadoAccesoContratoConRol {
            get {
                return ResourceManager.GetString("YaSeHaSolicitadoAccesoContratoConRol", resourceCulture);
            }
        }
        
        internal static string YaSeHaSolicitadoAccesoContratoConRolX {
            get {
                return ResourceManager.GetString("YaSeHaSolicitadoAccesoContratoConRolX", resourceCulture);
            }
        }
        
        internal static string ElUsuarioYaCuentaConAccesoAlContratoSolicitadoConRolX {
            get {
                return ResourceManager.GetString("ElUsuarioYaCuentaConAccesoAlContratoSolicitadoConRolX", resourceCulture);
            }
        }
        
        internal static string FechaHoraTerminoDebeSerMayorQueFechaHoraInicio {
            get {
                return ResourceManager.GetString("FechaHoraTerminoDebeSerMayorQueFechaHoraInicio", resourceCulture);
            }
        }
        
        internal static string ElElementoQueSeDeseaDesactivarYaSeEncuentraDesactivado {
            get {
                return ResourceManager.GetString("ElElementoQueSeDeseaDesactivarYaSeEncuentraDesactivado", resourceCulture);
            }
        }
        
        internal static string ElElementoQueSeDeseaActivarYaSeEncuentraActivo {
            get {
                return ResourceManager.GetString("ElElementoQueSeDeseaActivarYaSeEncuentraActivo", resourceCulture);
            }
        }
    }
}
